### PR TITLE
semaphore: Teach semThreadWait to use semWait with threaded RTS

### LINKED ISSUE #253: System.Posix.Semaphore.semThreadWait polls unnecessarily with threaded RTS
### Your environment

Which OS do you use: Any
Describe your project: Any

### Steps to reproduce
Currently the implementation of `System.Posix.Semaphore.semThreadWait` polls the semaphore in a tight loop to avoid blocking the entire process when using the non-threaded RTS. While this is necessary for the non-threaded RTS, there is no reason why we can't instead just block in a safe foreign call to `semWait` when the threaded RTS is in use.

### Expected behaviour
`semThreadWait` blocks when using the threaded RTS.

### Actual behaviour
`semThreadWait` polls.

### API breaking changes

This should be a strictly-internal change.

### Posix compliance

Nothing to note here.

### PR DESCRIPTION
**Pull request by bgamari**
semThreadWait uses a rather atrocious polling loop to avoid
blocking, which we block the entire program when using the non-threaded
runtime. However, this is unnecessary in the threaded runtime, where we
can instead simply block in semWait.

Fixes #253

### CODE REVIEW

**Comment by Bodigrim** [comment]
@bgamari please rebase atop of master, 2.7 series are no longer maintained. 
Also see https://gitlab.haskell.org/ghc/ghc/-/issues/22098

**Comment by sheaf** [comment]
@Bodigrim I've rebased. Could you take a look?

**Comment by Bodigrim** [comment]
@sheaf it says "This branch is 2 commits ahead, 4 commits behind haskell:master". Could you please rebase atop the latest master to get CI working?

**Review by hasufell — APPROVED** [review]

**Review by hs-viktor — APPROVED** [review]
LGTM, but we should first see a working CI run.

**Comment by Bodigrim** [comment]
I rebased it manually, but builds for GHC < 9.2 fail with
```
 System/Posix/Semaphore.hsc:32:32: error:
    Module ‘System.Posix.Internals’ does not export ‘hostIsThreaded’
   |
32 | import System.Posix.Internals (hostIsThreaded)
   |      
```
@bgamari @sheaf could you please fix this? E. g., by assuming that `hostIsThreaded = False` when GHC < 9.2. 
Cf. https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9376

**Comment by vdukhovni** [comment]
> I rebased it manually, but builds for GHC < 9.2 fail with
> 
> ```
>  System/Posix/Semaphore.hsc:32:32: error:
>     Module ‘System.Posix.Internals’ does not export ‘hostIsThreaded’
>    |
> 32 | import System.Posix.Internals (hostIsThreaded)
>    |      
> ```
> 
> @bgamari @sheaf could you please fix this? E. g., by assuming that `hostIsThreaded = False` when GHC < 9.2. Cf. https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9376

A somewhat better approximation of `hostIsThreaded` for GHC < 9.2 could be to test the return value of `getNumCapabilities` to see whether it is larger than 1.

**Comment by Bodigrim** [comment]
Also @TerrorJack could you please take a look at WASM build?
```
wasm-ld: warning: /home/runner/work/unix/unix/dist-newstyle/build/wasm32-wasi/ghc-9.5.20221111/unix-2.8.0.0/build/libHSunix-2.8.0.0-inplace.a(ghc_120.o): undefined symbol: sem_post
wasm-ld: warning: /home/runner/work/unix/unix/dist-newstyle/build/wasm32-wasi/ghc-9.5.20221111/unix-2.8.0.0/build/libHSunix-2.8.0.0-inplace.a(ghc_120.o): undefined symbol: sem_trywait
wasm-ld: warning: /home/runner/work/unix/unix/dist-newstyle/build/wasm32-wasi/ghc-9.5.20221111/unix-2.8.0.0/build/libHSunix-2.8.0.0-inplace.a(ghc_120.o): undefined symbol: sem_wait
wasm-ld: warning: /home/runner/work/unix/unix/dist-newstyle/build/wasm32-wasi/ghc-9.5.20221111/unix-2.8.0.0/build/libHSunix-2.8.0.0-inplace.a(ghc_120.o): undefined symbol: sem_close
wasm-ld: warning: /home/runner/work/unix/unix/dist-newstyle/build/wasm32-wasi/ghc-9.5.20221111/unix-2.8.0.0/build/libHSunix-2.8.0.0-inplace.a(ghc_120.o): undefined symbol: sem_open
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
```

**Comment by TerrorJack** [comment]
Apologies for slow responses on `unix`; I'm on holiday and will be back by end of this week. I'll take a deeper look and fix CI by then, and before that to unblock work you could insert a `exit 0` in the pipeline early for the time being @Bodigrim

**Comment by TerrorJack** [comment]
Thanks @sheaf for the fix. Yes, skipping semaphore tests make sense since the `sem_*` functions aren't present in `wasi-libc` anyway.

File: tests/Semaphore002.hs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+module Main (main) where
+
+import Control.Concurrent
+import System.Posix
+
+main :: IO ()
+main = do
+  sem <- semOpen "/test" OpenSemFlags {semCreate = True, semExclusive = False} stdFileMode 0
+  forkIO $ do
```
Comment (Bodigrim) [inline tests/Semaphore002.hs:9]: This triggers a warning "A do-notation statement discarded a result of type ‘ThreadId’".

**Comment by Bodigrim** [comment]
Merging despite CI failures, they are unrelated. 
(Apparently `ubuntu-latest` is now `ubuntu-22.04` and something is wrong again: https://github.com/haskell/unix/actions/runs/3623339690/jobs/6109094742#step:3:148)

**Review by Bodigrim — APPROVED** [review]
